name: Call a reusable deploy workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-workflow:
    uses: Faraz-Portfolio/demo-template/.github/workflows/deploy.yml@main
